# Generated by Django 4.2 on 2025-11-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='owner_id',
            field=models.CharField(default=123455678, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posthistory',
            name='actor_id',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
