# Generated by Django 4.2 on 2025-12-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bumped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='vip_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
