# Generated by Django 4.2 on 2025-12-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_post_bumped_at_post_is_vip_post_vip_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBumpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(max_length=9)),
                ('is_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.ForeignKey(db_column='post_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bump_logs', to='listings.post')),
            ],
            options={
                'db_table': 'listings_postbumplog',
            },
        ),
        migrations.AddIndex(
            model_name='postbumplog',
            index=models.Index(fields=['post', 'created_at'], name='listings_po_post_id_37c0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='postbumplog',
            index=models.Index(fields=['actor_id', 'created_at'], name='listings_po_actor_i_a7a561_idx'),
        ),
    ]
