# Generated by Django 4.2 on 2025-12-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_postbumplog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vip_expired_at',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-bumped_at'], name='listings_po_bumped__0ae01f_idx'),
        ),
        migrations.AlterModelTable(
            name='postbumplog',
            table=None,
        ),
    ]
