# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_remove_post_is_vip_remove_post_vip_expired_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostBumpSchedule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("owner_id", models.CharField(max_length=9)),
                ("run_time", models.TimeField()),
                ("timezone", models.CharField(default="Asia/Ho_Chi_Minh", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused")], default="active", max_length=16)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("fail_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bump_schedules",
                        to="listings.post",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner_id", "is_active"], name="listings_po_owner_i_5b6d19_idx"),
                    models.Index(fields=["next_run_at"], name="listings_po_next_ru_8d6a4a_idx"),
                ],
            },
        ),
    ]
