# Generated by Django 4.2 on 2025-12-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_post_is_vip_remove_post_vip_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner_is_agent',
            field=models.BooleanField(default=False, help_text='Owner là AGENT (VIP) tại thời điểm đăng bài'),
        ),
    ]
