# Generated by Codex on 2026-01-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_post_owner_is_agent"),
        ("listings", "0007_postbumpschedule"),
    ]

    operations = [
    ]
