# Generated by Django 4.2 on 2025-12-04 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã gói, ví dụ: AGENT_1M, AGENT_3M', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên gói hiển thị cho người dùng', max_length=255)),
                ('price_vnd', models.BigIntegerField(help_text='Giá gói (VND)')),
                ('duration_days', models.PositiveIntegerField(help_text='Thời gian hiệu lực (ngày), ví dụ 30, 90, 365')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'membership_plan',
                'ordering': ['price_vnd'],
            },
        ),
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vnd', models.BigIntegerField(help_text='Số tiền cần thanh toán (VND)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('bank_ref', models.CharField(blank=True, help_text='Mã giao dịch ngân hàng (admin nhập tay / webhook)', max_length=255, null=True)),
                ('transfer_note', models.CharField(help_text='Nội dung chuyển khoản dùng để đối soát, ví dụ: UPGRADE_USER_3_ORDER_5', max_length=255)),
                ('qr_image_url', models.URLField(blank=True, help_text='Link ảnh QR VietQR', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_order',
            },
        ),
        migrations.AddIndex(
            model_name='membershiporder',
            index=models.Index(fields=['user'], name='membership__user_id_94054e_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiporder',
            index=models.Index(fields=['status'], name='membership__status_d55e79_idx'),
        ),
    ]
