# Generated by Django 4.2 on 2025-12-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membershipplan_membershiporder_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membershipplan',
            table=None,
        ),
    ]
