# Generated by Django 4.2 on 2025-12-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membershipplan_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membershiporder',
            new_name='accounts_me_user_id_6f68c5_idx',
            old_name='membership__user_id_94054e_idx',
        ),
        migrations.RenameIndex(
            model_name='membershiporder',
            new_name='accounts_me_status_d9a118_idx',
            old_name='membership__status_d55e79_idx',
        ),
        migrations.AlterModelTable(
            name='membershiporder',
            table=None,
        ),
    ]
