# Generated by Django 4.2 on 2025-12-08 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_membership__user_id_94054e_idx_accounts_me_user_id_6f68c5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('last_bump_date', models.DateField(blank=True, null=True)),
                ('bumps_used_today', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_memberships', to='accounts.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user'], name='accounts_us_user_id_91ddf5_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['expired_at'], name='accounts_us_expired_1c76f0_idx'),
        ),
    ]
