# Generated by Django 4.2 on 2026-01-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
    ]
