# Generated by Django 4.2 on 2025-11-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=9)),
                ('user_id', models.CharField(max_length=9)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=9)),
                ('user_id', models.CharField(max_length=9)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=9)),
                ('post_id', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
            ],
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user_id'], name='engagement__user_id_a4b193_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['post_id'], name='engagement__post_id_369ee4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user_id', 'post_id')},
        ),
        migrations.AddIndex(
            model_name='postrating',
            index=models.Index(fields=['user_id'], name='engagement__user_id_0aba1f_idx'),
        ),
        migrations.AddIndex(
            model_name='postrating',
            index=models.Index(fields=['post_id'], name='engagement__post_id_cb7e4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postrating',
            unique_together={('user_id', 'post_id')},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.comment'),
        ),
    ]
