# Generated by Django 4.2 on 2025-12-01 03:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=9)),
                ('post_id', models.CharField(db_index=True, max_length=9)),
                ('content', models.TextField(db_column='noi_dung')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], db_column='trang_thai', default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='ngay_sua')),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=9, null=True)),
                ('post_id', models.CharField(db_index=True, max_length=9)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_xem')),
            ],
            options={
                'db_table': 'eng_post_view',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RenameIndex(
            model_name='postrating',
            new_name='eng_post_ra_post_id_a533a6_idx',
            old_name='engagement__post_id_cb7e4e_idx',
        ),
        migrations.RenameIndex(
            model_name='postrating',
            new_name='eng_post_ra_user_id_e07da7_idx',
            old_name='engagement__user_id_0aba1f_idx',
        ),
        migrations.RemoveField(
            model_name='postrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='postrating',
            name='score',
            field=models.SmallIntegerField(db_column='diem', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='postrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='ngay_sua'),
        ),
        migrations.AlterField(
            model_name='postrating',
            name='comment',
            field=models.TextField(blank=True, db_column='binh_luan', null=True),
        ),
        migrations.AlterField(
            model_name='postrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao'),
        ),
        migrations.AlterField(
            model_name='postrating',
            name='post_id',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='postrating',
            name='user_id',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterModelTable(
            name='postrating',
            table='eng_post_rating',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post_id'], name='eng_post_vi_post_id_7d3d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user_id'], name='eng_post_vi_user_id_53af5a_idx'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.postcomment'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post_id'], name='engagement__post_id_bebe9a_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['user_id'], name='engagement__user_id_7661eb_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['status'], name='engagement__trang_t_ab4b1d_idx'),
        ),
    ]
