# Generated by Django 4.2 on 2025-12-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_postcomment_postview_remove_comment_parent_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postview',
            new_name='engagement__post_id_6fc0b5_idx',
            old_name='eng_post_vi_post_id_7d3d1f_idx',
        ),
        migrations.RenameIndex(
            model_name='postview',
            new_name='engagement__user_id_060e9d_idx',
            old_name='eng_post_vi_user_id_53af5a_idx',
        ),
        migrations.AlterModelTable(
            name='postview',
            table=None,
        ),
    ]
