# Generated by Django 4.2 on 2025-12-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_rename_eng_post_vi_post_id_7d3d1f_idx_engagement__post_id_6fc0b5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postrating',
            new_name='engagement__post_id_cb7e4e_idx',
            old_name='eng_post_ra_post_id_a533a6_idx',
        ),
        migrations.RenameIndex(
            model_name='postrating',
            new_name='engagement__user_id_0aba1f_idx',
            old_name='eng_post_ra_user_id_e07da7_idx',
        ),
        migrations.AlterModelTable(
            name='postrating',
            table=None,
        ),
    ]
