# Generated by Django 4.2 on 2025-10-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ho_ten',
        ),
        migrations.AddField(
            model_name='user',
            name='cccd_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
