# Generated by Django 4.2 on 2025-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='listing_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
