# Generated by Django 4.2 on 2026-01-14 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_alter_chatroom_listing_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('buyer', 'seller', 'listing_id')},
        ),
    ]
